[package]
name = "nam"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
nice-plug = { version = "0.3.0", default-features = false }
neural-amp-modeler-rs = { package = "NeuralAmpModeler-rs", version = "0.6.0" }
rfd = "0.15"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
